[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn bot:app --bind 0.0.0.0:$PORT --worker-class aiohttp.worker.GunicornWebWorker --workers 4 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckInterval = 10 