[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn bot:app --host 0.0.0.0 --port $PORT --workers 4 --timeout-keep-alive 120"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckInterval = 10 